[dev]
  command = "npm run build"
  port = 8888
  targetPort = 3000
  publish = "dist" 
  jwtRolePath = "app_metadata.authorization.roles"
  jwtSecret = "MY_JWT_SECRET_VALUE"
  autoLaunch = true
  framework = "#custom"